name: 'Create Web'

on:

  pull_request:
    branches: [ main ]

jobs:

  terraform:

    run-on: ubuntu-latest

    steps:
      
    - uses: action/checkout@v2

    - name: Checkout
      uses: actions/checkout@v2  

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
    
    - name: Terraform Init
      run: terraform init

